

#  PERFIL: dev
#  Se activa con: spring.profiles.active=dev


# En dev mostramos SQL formateado y mas logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DDL en dev: update
spring.jpa.hibernate.ddl-auto=update

# Swagger habilitado en dev
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Logs
logging.level.com.incidentreport=DEBUG
logging.level.org.springframework.security=DEBUG