
#  PERFIL: prod
#  Se activa con: spring.profiles.active=prod
#  o con la variable de entorno: SPRING_PROFILES_ACTIVE=prod

# En prod NO mostrar SQL
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# DDL en prod: validate
spring.jpa.hibernate.ddl-auto=validate

# Swagger DESHABILITADO en prod
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

# Logs
logging.level.root=WARN
logging.level.com.incidentreport=INFO
logging.level.org.springframework.security=WARN